// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCr7KOXC5GGz7ITyKbU0a8z_ariNnHWQyI',
    appId: '1:246642385825:web:d85dc7e30046767a9921e0',
    messagingSenderId: '246642385825',
    projectId: 'mega-cheap-data',
    authDomain: 'mega-cheap-data.firebaseapp.com',
    databaseURL: 'https://mega-cheap-data.firebaseio.com',
    storageBucket: 'mega-cheap-data.appspot.com',
    measurementId: 'G-9KN9ZK7PHT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB4bCAxYWuDE62rsiMKXSdgJRxeAjDG0To',
    appId: '1:246642385825:android:6f1671742642f61d',
    messagingSenderId: '246642385825',
    projectId: 'mega-cheap-data',
    databaseURL: 'https://mega-cheap-data.firebaseio.com',
    storageBucket: 'mega-cheap-data.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAIrwfumuf7W7iStNl8RHI-7pPtKg2x1jA',
    appId: '1:246642385825:ios:d54da772d2dec2ee9921e0',
    messagingSenderId: '246642385825',
    projectId: 'mega-cheap-data',
    databaseURL: 'https://mega-cheap-data.firebaseio.com',
    storageBucket: 'mega-cheap-data.appspot.com',
    androidClientId: '246642385825-khms495ln6n0tkgbdek3s155sv7vvemr.apps.googleusercontent.com',
    iosClientId: '246642385825-f522liust25qb7r3vgja85tno0qjhtl8.apps.googleusercontent.com',
    iosBundleId: 'a5starcompany.com.megacheapdata',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAIrwfumuf7W7iStNl8RHI-7pPtKg2x1jA',
    appId: '1:246642385825:ios:d54da772d2dec2ee9921e0',
    messagingSenderId: '246642385825',
    projectId: 'mega-cheap-data',
    databaseURL: 'https://mega-cheap-data.firebaseio.com',
    storageBucket: 'mega-cheap-data.appspot.com',
    androidClientId: '246642385825-khms495ln6n0tkgbdek3s155sv7vvemr.apps.googleusercontent.com',
    iosClientId: '246642385825-f522liust25qb7r3vgja85tno0qjhtl8.apps.googleusercontent.com',
    iosBundleId: 'a5starcompany.com.megacheapdata',
  );
}
